const imageBase='https://lh3.googleusercontent.com/d/';
const products=[
 {id:'C0002',name:'白水晶・茶晶・黃水晶純銀手鏈',price:528,cat:'crystal',stock:3,img:'fallback'},
 {id:'C0003',name:'海藍寶・天河石・白水晶手鏈',price:478,cat:'crystal',stock:4,img:'fallback'},
 {id:'C0009',name:'白月光石・白水晶・海藍寶手鏈',price:368,cat:'crystal',stock:6,img:'fallback'},
 {id:'E0033',name:'蝴蝶結飄帶耳環',price:268,cat:'earrings',stock:8,img:'1oowUr6PtntLUdvPZeWQCzyhs4Mp9UemSIMn6yFqqs755jR0'},
 {id:'R0049',name:'月光石開口戒指',price:168,cat:'rings',stock:4,img:'1LroB4Ev7OLU8Mt6CwGEvbUQnIS0n2qy_6hkw_eYwW17yU0g'},
 {id:'N0026',name:'天然貝母頸鏈',price:278,cat:'necklaces',stock:6,img:'1-uKgMijIj6wmW8XqDgetiPezIAcPKT5s83N1oIA_roi_wCM'},
 {id:'H0024',name:'天然珍珠手鏈',price:238,cat:'bracelets',stock:2,img:'1O4LhAxc9tn5YaEZWQfxWMksBEcKvq8dkfJXzd_DObXW9x8Q'},
 {id:'E0038',name:'磨砂銀大水滴耳環',price:238,cat:'earrings',stock:0,preorder:true,img:'1A7Cg4aHw7yO2ToRx5LhaQ5dMEDGsmqZCllYJEXPXqIXx7pI'},
 {id:'R0012',name:'鏤空蕾絲月光石戒指',price:178,cat:'rings',stock:7,img:'1ZRsoDTODyjJpfpuIyYQQ_sBZmd3hHz0FUTzQ5dEdlox96YY'},
 {id:'N0023',name:'海藍寶銀管頸鏈',price:338,cat:'necklaces',stock:1,img:'1pRoW7EXLuOZcLs2wkuS95YX8dkxPQSgAsueyFmBPp9Eg0xE'},
 {id:'C0007',name:'海藍寶海星純銀手鏈',price:328,cat:'bracelets',stock:5,img:'fallback'}
];
const defaultDiscount={enabled:true,productId:'C0002',salePrice:449,code:'MUSIS10',codePercent:10,minSpend:300,start:'2026-10-01',end:'2026-10-31'};
let discountSettings={...defaultDiscount,...JSON.parse(localStorage.getItem('musis-discount')||'{}')};
const defaultAnnouncements=['澳門滿 MOP 300 免運 · 香港滿 MOP 500 免運','預訂款約 7 個工作天到貨','限時優惠進行中 · 結帳輸入優惠碼 MUSIS10'];
let announcements=JSON.parse(localStorage.getItem('musis-announcements')||'null')||defaultAnnouncements;
const defaultAbout={title:'為日常而生的銀飾。',body:'MUSIS 從澳門出發，挑選適合每天佩戴的 925 純銀飾品。這個網站讓品牌故事、保養資訊與購物流程自然連接。',careTitle:'保養提示',careBody:'避免與香水及化學品直接接觸；不佩戴時放入密封袋，輕微氧化可使用拭銀布清潔。',image:'assets/musis-hero-2.jpg'};
let aboutSettings={...defaultAbout,...JSON.parse(localStorage.getItem('musis-about')||'{}')};
const defaultRingSizes={R0049:['均碼・開口戒'],R0012:['均碼・開口戒']};
let ringSizeSettings={...defaultRingSizes,...JSON.parse(localStorage.getItem('musis-ring-sizes')||'{}')};
let cart=JSON.parse(localStorage.getItem('musis-cart')||'[]');
let favorites=JSON.parse(localStorage.getItem('musis-favorites')||'[]');
let heroCarouselTimer,announcementTimer,checkoutCartSync=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function money(n){return `MOP ${n.toLocaleString('en-US')}`}
function discountActive(){const today=new Date().toISOString().slice(0,10);return discountSettings.enabled&&today>=discountSettings.start&&today<=discountSettings.end}
function productPrice(p){return discountActive()&&p.id===discountSettings.productId?Number(discountSettings.salePrice):p.price}
function startAnnouncementCarousel(){clearInterval(announcementTimer);const node=$('#announcementText'),items=announcements.filter(Boolean);if(!node||!items.length)return;let index=0;const show=()=>{node.classList.add('changing');setTimeout(()=>{node.textContent=items[index];node.classList.remove('changing');index=(index+1)%items.length},180)};node.textContent=items[0];index=items.length>1?1:0;if(items.length>1)announcementTimer=setInterval(show,4000)}
function imageStyle(p,i){const valid=p.img.length>25;return valid?`--img:url('${imageBase}${p.img}=w900')`:`--img:url('assets/musis-hero.png');background-position:${35+i*7}% center`}
function heartSvg(saved=false){return `<svg class="heart-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21.2 3.5 12.5C.8 9.7 1.3 5.3 4.4 3.2c2.5-1.7 5.8-1.1 7.6 1.3 1.8-2.4 5.1-3 7.6-1.3 3.1 2.1 3.6 6.5.9 9.3L12 21.2Z"${saved?' fill="currentColor"':''}/></svg>`}
function productCard(p,i=0){const saved=favorites.includes(p.id),sale=productPrice(p)<p.price;return `<article class="product-card" data-id="${p.id}"><div class="product-visual" style="${imageStyle(p,i)}">${sale?'<span class="badge sale-badge">SALE</span>':p.preorder?'<span class="badge">PRE-ORDER</span>':p.stock<=2?'<span class="badge">LOW STOCK</span>':''}<button class="favorite-button ${saved?'saved':''}" data-favorite="${p.id}" aria-label="${saved?'取消收藏':'收藏'} ${p.name}">${heartSvg(saved)}</button><button class="quick-add" aria-label="加入 ${p.name}">＋</button></div><div class="product-info"><small>${p.id} · 925 SILVER</small><h3>${p.name}</h3><p class="product-price">${sale?`<del>${money(p.price)}</del><strong>${money(productPrice(p))}</strong>`:money(p.price)}</p></div></article>`}
function bindProductCards(){ $$('.product-card').forEach(card=>{card.querySelector('.quick-add').onclick=e=>{e.stopPropagation();addToCart(card.dataset.id)};card.querySelector('.favorite-button').onclick=e=>{e.stopPropagation();toggleFavorite(card.dataset.id,e.currentTarget)};card.onclick=()=>location.hash=`product?id=${card.dataset.id}`}); }
const PAGE_SIZE=12;
function renderPagination(container,totalPages,currentPage,onChange){if(!container)return;if(totalPages<=1){container.innerHTML='';return}container.innerHTML=`<button ${currentPage===1?'disabled':''} data-page="${currentPage-1}">← 上一頁</button>${Array.from({length:totalPages},(_,i)=>`<button class="${i+1===currentPage?'active':''}" data-page="${i+1}">${i+1}</button>`).join('')}<button ${currentPage===totalPages?'disabled':''} data-page="${currentPage+1}">下一頁 →</button>`;container.querySelectorAll('[data-page]:not([disabled])').forEach(button=>button.onclick=()=>onChange(Number(button.dataset.page)))}
function productSizes(p){return p.cat==='rings'&&Array.isArray(ringSizeSettings[p.id])&&ringSizeSettings[p.id].length?ringSizeSettings[p.id]:p.cat==='rings'?['均碼・開口戒']:[]}
function addToCart(id,size=''){const p=products.find(x=>x.id===id),chosen=size||(productSizes(p)[0]||''),row=cart.find(x=>x.id===id&&(x.size||'')===chosen);row?row.qty++:cart.push({id,qty:1,...(chosen?{size:chosen}:{})});saveCart();toast('已加入購物清單');openCart()}
function saveFavorites(){localStorage.setItem('musis-favorites',JSON.stringify(favorites));const count=$('#favoritesCount');if(count)count.textContent=favorites.length}
function toggleFavorite(id,button){const saved=favorites.includes(id);favorites=saved?favorites.filter(x=>x!==id):[...favorites,id];saveFavorites();if(button){const active=!saved;button.classList.toggle('saved',active);button.innerHTML=button.classList.contains('detail-favorite')?`${heartSvg(active)}<span>${active?'已收藏':'收藏'}</span>`:heartSvg(active);button.setAttribute('aria-label',active?'取消收藏':'收藏')}toast(saved?'已取消收藏':'已加入收藏')}
function saveCart(){localStorage.setItem('musis-cart',JSON.stringify(cart));$('#cartCount').textContent=cart.reduce((n,x)=>n+x.qty,0);renderCart();if(checkoutCartSync&&$('#checkoutForm'))checkoutCartSync()}
function cartSubtotal(){return cart.reduce((n,x)=>{const p=products.find(v=>v.id===x.id);return n+(p?productPrice(p):0)*x.qty},0)}
function renderCart(){const box=$('#cartItems');if(!box)return;box.innerHTML=cart.length?cart.map((x,index)=>{const p=products.find(v=>v.id===x.id),sale=productPrice(p)<p.price;return `<div class="cart-row"><div class="cart-thumb"></div><div><small>${p.id}${x.size?` · ${x.size}`:''}</small><h4>${p.name}</h4><b>${sale?`<del>${money(p.price)}</del> ${money(productPrice(p))}`:money(p.price)}</b><div class="qty"><button data-delta="-1" data-index="${index}">−</button><span>${x.qty}</span><button data-delta="1" data-index="${index}">＋</button></div></div><button class="remove" data-remove="${index}">×</button></div>`}).join(''):'<div class="empty">購物清單還是空的<br><small>選一件會陪你很久的銀飾。</small></div>';const sub=cartSubtotal();$('#cartSubtotal').textContent=money(sub);$('#shippingBar').style.width=`${Math.min(100,sub/300*100)}%`;$('#shippingMessage').textContent=sub>=300?'已享澳門免運':`再選購 ${money(300-sub)} 即享澳門免運`;box.querySelectorAll('[data-delta]').forEach(b=>b.onclick=()=>{const index=Number(b.dataset.index),row=cart[index];row.qty+=+b.dataset.delta;if(row.qty<1)cart.splice(index,1);saveCart()});box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.remove),1);saveCart()})}
function openCart(){if(location.hash.startsWith('#admin'))return;$('#cartDrawer').classList.add('open');$('#cartDrawer').setAttribute('aria-hidden','false');$('#cartButton').setAttribute('aria-expanded','true');$('#scrim').classList.add('open')}
function closeDrawers(){$('#cartDrawer').classList.remove('open');$('#cartDrawer').setAttribute('aria-hidden','true');$('#cartButton').setAttribute('aria-expanded','false');$('#mobileDrawer').classList.remove('open');$('#scrim').classList.remove('open')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function bindHeroCarousel(){const slides=$$('.hero-slide'),dots=$$('.hero-dots button');if(!slides.length)return;let active=0;const show=i=>{active=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle('active',n===active));dots.forEach((d,n)=>d.classList.toggle('active',n===active))};const play=()=>{clearInterval(heroCarouselTimer);heroCarouselTimer=setInterval(()=>show(active+1),5200)};$('.hero-arrow.prev').onclick=()=>{show(active-1);play()};$('.hero-arrow.next').onclick=()=>{show(active+1);play()};dots.forEach((d,i)=>d.onclick=()=>{show(i);play()});$('.hero-image').onmouseenter=()=>clearInterval(heroCarouselTimer);$('.hero-image').onmouseleave=play;play()}
function renderHome(){const node=$('#homeTemplate').content.cloneNode(true);$('#app').replaceChildren(node);$('#featuredGrid').innerHTML=products.slice(0,4).map(productCard).join('');$('#bestsellerGrid').innerHTML=[products[4],products[7],products[5],products[9]].map(productCard).join('');bindProductCards();bindHeroCarousel();showChrome(true)}
function renderShop(){
  const node=$('#shopTemplate').content.cloneNode(true);$('#app').replaceChildren(node);showChrome(true);
  const labels={all:'全部',crystal:'水晶系列',earrings:'耳環',rings:'戒指',necklaces:'頸鏈',bracelets:'手鏈'};
  const titles={all:['全部商品','ALL PRODUCTS'],crystal:['水晶','CRYSTAL'],earrings:['耳環','EARRINGS'],rings:['戒指','RINGS'],necklaces:['頸鏈','NECKLACES'],bracelets:['手鏈','BRACELETS']};
  const params=new URLSearchParams(location.hash.split('?')[1]||'');let active=params.get('cat')||'all',currentPage=1;
  $('#filters').innerHTML=Object.entries(labels).map(([k,v])=>`<button class="filter ${k===active?'active':''}" data-cat="${k}">${v}</button>`).join('');
  const draw=()=>{
    const [zh,en]=titles[active]||titles.all;$('#shopHeading').innerHTML=`<h1 class="collection-title"><span>${zh}</span><span>${en}</span></h1>`;
    const q=$('#searchInput').value.trim().toLowerCase(),sort=$('#sortSelect').value;
    const list=products.filter(p=>(active==='all'||p.cat===active)&&p.name.toLowerCase().includes(q));
    if(sort==='price-asc')list.sort((a,b)=>productPrice(a)-productPrice(b));if(sort==='price-desc')list.sort((a,b)=>productPrice(b)-productPrice(a));
    const totalPages=Math.max(1,Math.ceil(list.length/PAGE_SIZE)),pageItems=list.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE);
    $('#catalogGrid').innerHTML=pageItems.length?pageItems.map(productCard).join(''):'<p class="empty">找不到符合的商品</p>';bindProductCards();renderPagination($('#catalogPagination'),totalPages,currentPage,page=>{currentPage=page;draw();$('#shopHeading').scrollIntoView({behavior:'smooth'})});
  };
  draw();$$('.filter').forEach(b=>b.onclick=()=>{active=b.dataset.cat;currentPage=1;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));draw()});$('#searchInput').oninput=()=>{currentPage=1;draw()};$('#sortSelect').onchange=()=>{currentPage=1;draw()};
}
function renderCollection(type){showChrome(true);const isNew=type==='new',source=isNew?products:[products[4],products[7],products[5],products[9]];let currentPage=1;$('#app').innerHTML=`<section class="shop-head collection-head" id="collectionHeading"><h1 class="collection-title"><span>${isNew?'新品':'熱銷商品'}</span><span>${isNew?'NEW ARRIVALS':'BEST'}</span></h1><p>${isNew?'最新加入 MUSIS 的日常銀飾。':'最多客人選擇、適合日常佩戴的款式。'}</p></section><section class="shop-controls collection-controls"><div></div><div class="shop-tools"><label class="sort-control"><span>排序</span><select id="collectionSort"><option value="newest">最新上架</option><option value="price-asc">價格由低至高</option><option value="price-desc">價格由高至低</option></select></label><label class="search"><svg class="search-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.8"></circle><path d="m16 16 5 5"></path></svg><span>搜尋</span><input id="collectionSearch" placeholder="輸入商品名稱"></label></div></section><section class="catalog product-grid" id="collectionGrid"></section><nav class="pagination" id="collectionPagination" aria-label="商品分頁"></nav>`;const draw=()=>{const q=$('#collectionSearch').value.trim().toLowerCase(),sort=$('#collectionSort').value,list=source.filter(p=>p.name.toLowerCase().includes(q));if(sort==='price-asc')list.sort((a,b)=>productPrice(a)-productPrice(b));if(sort==='price-desc')list.sort((a,b)=>productPrice(b)-productPrice(a));const totalPages=Math.max(1,Math.ceil(list.length/PAGE_SIZE)),pageItems=list.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE);$('#collectionGrid').innerHTML=pageItems.length?pageItems.map(productCard).join(''):'<p class="empty">找不到符合的商品</p>';bindProductCards();renderPagination($('#collectionPagination'),totalPages,currentPage,page=>{currentPage=page;draw();$('#collectionHeading').scrollIntoView({behavior:'smooth'})})};$('#collectionSearch').oninput=()=>{currentPage=1;draw()};$('#collectionSort').onchange=()=>{currentPage=1;draw()};draw()}
function renderNew(){renderCollection('new')}
function renderHot(){renderCollection('hot')}
function renderFavorites(){showChrome(true);let currentPage=1;$('#app').innerHTML=`<section class="shop-head collection-head" id="favoritesHeading"><h1 class="collection-title"><span>收藏</span><span>WISHLIST</span></h1><p>收藏會保存在這部裝置的瀏覽器中。</p></section><section class="catalog product-grid" id="favoritesGrid"></section><nav class="pagination" id="favoritesPagination" aria-label="收藏分頁"></nav>`;const draw=()=>{const list=favorites.map(id=>products.find(p=>p.id===id)).filter(Boolean),totalPages=Math.max(1,Math.ceil(list.length/PAGE_SIZE)),pageItems=list.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE);$('#favoritesGrid').innerHTML=pageItems.length?pageItems.map(productCard).join(''):'<div class="empty favorites-empty">還沒有收藏商品<br><small>在商品圖片點擊愛心，喜歡的款式便會留在這裡。</small><br><a class="primary" href="#new">看看新品 →</a></div>';bindProductCards();$$('#favoritesGrid .favorite-button').forEach(button=>button.onclick=e=>{e.stopPropagation();toggleFavorite(button.dataset.favorite);draw()});renderPagination($('#favoritesPagination'),totalPages,currentPage,page=>{currentPage=page;draw();$('#favoritesHeading').scrollIntoView({behavior:'smooth'})})};draw()}
function renderProduct(){
  showChrome(true);
  const id=new URLSearchParams(location.hash.split('?')[1]||'').get('id');
  const p=products.find(x=>x.id===id)||products[0],saved=favorites.includes(p.id);
  const categoryNames={crystal:'天然水晶與 925 純銀',earrings:'925 純銀耳環',rings:'925 純銀戒指',necklaces:'925 純銀頸鏈',bracelets:'925 純銀手鏈'};
  const categorySpecs={crystal:['天然水晶，每件紋理略有不同','彈性手圍，尺寸可於下單時備註'],earrings:['成對發售','附耳塞及獨立密封袋'],rings:['開口設計，可輕微調節','避免反覆大幅拉扯戒圍'],necklaces:['附可調節延長鏈','佩戴後請以軟布輕拭'],bracelets:['附可調節延長鏈','佩戴後請以軟布輕拭']};
  const specs=categorySpecs[p.cat]||['925 通體純銀','附獨立密封袋'];
  const related=products.filter(x=>x.id!==p.id&&(x.cat===p.cat||x.cat==='crystal')).slice(0,4);
  const galleryImage=p.img.length>25?`--img:url('${imageBase}${p.img}=w1200')`:`--img:url('assets/musis-hero.png')`;
  $('#app').innerHTML=`<section class="product-page">
    <div class="product-gallery">
      <div class="product-detail-image" id="productMainImage" style="${galleryImage};--detail-pos:35% center" role="img" aria-label="${p.name}"></div>
      <div class="product-gallery-footer"><div class="product-thumbs" aria-label="商品圖片">
        <button class="active" data-pos="35% center" aria-label="查看商品主圖"><span style="${imageStyle(p,0)}"></span></button>
        <button data-pos="52% center" aria-label="查看商品細節"><span style="${imageStyle(p,1)}"></span></button>
        <button data-pos="72% center" aria-label="查看佩戴細節"><span style="${imageStyle(p,2)}"></span></button>
      </div><span id="galleryCount">1 / 3</span></div>
    </div>
    <div class="product-detail-copy">
      <a href="#shop?cat=${p.cat}" class="eyebrow">← 返回商品列表</a>
      <p class="eyebrow">${p.id} · ${categoryNames[p.cat]||'925 STERLING SILVER'}</p>
      <h1>${p.name}</h1><p class="detail-price">${productPrice(p)<p.price?`<del>${money(p.price)}</del><strong>${money(productPrice(p))}</strong>`:money(p.price)}</p>
      ${productPrice(p)<p.price?`<p class="sale-message">期間限定優惠 · 至 ${discountSettings.end}</p>`:''}
      <p class="detail-copy">柔和銀光與輕巧輪廓，適合每天佩戴。商品圖片為實物拍攝；天然水晶的色澤與紋理會略有不同。</p>
      <div class="purchase-notes"><span>${p.preorder?'預訂款 · 約 7 個工作天到貨':p.stock<=2?`現貨 · 僅餘 ${p.stock} 件`:'現貨供應'}</span><span class="shipping-thresholds">澳門滿 MOP 300 免運 · 香港滿 MOP 500 免運</span></div>
      <div class="detail-line"><span>材質</span><b>925 通體純銀</b></div>
      ${p.cat==='rings'?`<div class="ring-size-row"><span>尺寸</span><div class="ring-size-options" id="ringSizeOptions">${productSizes(p).map((size,index)=>`<button type="button" class="${index===0?'selected':''}" data-size="${size}">${size}</button>`).join('')}</div></div>`:''}
      <div class="quantity-row"><span>數量</span><div class="detail-qty"><button id="qtyMinus" aria-label="減少數量">−</button><b id="detailQty">1</b><button id="qtyPlus" aria-label="增加數量">＋</button></div></div>
      <div class="detail-actions"><button class="primary" id="detailAdd">加入購物清單</button><button class="detail-favorite ${saved?'saved':''}" id="detailFavorite">${heartSvg(saved)}<span>${saved?'已收藏':'收藏'}</span></button></div>
      <div class="product-accordions">
        <details open><summary>產品規格 <span>＋</span></summary><ul><li>${specs[0]}</li><li>${specs[1]}</li><li>每件附保養說明及收納密封袋</li></ul></details>
        <details><summary>材質與保養 <span>＋</span></summary><p>925 純銀會隨時間自然氧化。避免接觸香水、乳液及化學品；不佩戴時保持乾燥並密封保存，氧化後以拭銀布輕擦。</p></details>
        <details><summary>配送與取貨 <span>＋</span></summary><p>澳門可選 eBuy 取貨點或智能櫃；香港使用順豐。結帳時系統會按地區與訂單金額顯示「順豐到付」或「順豐寄付」。</p></details>
        <details><summary>退換說明 <span>＋</span></summary><p>如收到品質異常或錯誤商品，請在收貨後 7 日內聯絡我們。耳環基於衛生理由，非品質問題不設退換。</p></details>
      </div>
    </div>
  </section>
  <section class="related-products"><div class="section-heading"><div><p class="eyebrow">YOU MAY ALSO LIKE</p><h2>你可能也喜歡</h2></div><a href="#shop?cat=${p.cat}">查看同系列 →</a></div><div class="product-grid" id="relatedGrid">${related.map(productCard).join('')}</div></section>`;
  let qty=1;
  let selectedSize=productSizes(p)[0]||'';
  $$('#ringSizeOptions button').forEach(button=>button.onclick=()=>{selectedSize=button.dataset.size;$$('#ringSizeOptions button').forEach(x=>x.classList.toggle('selected',x===button))});
  $('#qtyMinus').onclick=()=>{$('#detailQty').textContent=qty=Math.max(1,qty-1)};
  $('#qtyPlus').onclick=()=>{$('#detailQty').textContent=qty=Math.min(10,qty+1)};
  $('#detailAdd').onclick=()=>{const row=cart.find(x=>x.id===p.id&&(x.size||'')===selectedSize);row?row.qty+=qty:cart.push({id:p.id,qty,...(selectedSize?{size:selectedSize}:{})});saveCart();toast(`已加入 ${qty} 件商品${selectedSize?` · ${selectedSize}`:''}`);openCart()};
  $('#detailFavorite').onclick=e=>toggleFavorite(p.id,e.currentTarget);
  $$('.product-thumbs button').forEach((button,index)=>button.onclick=()=>{const main=$('#productMainImage');main.style.setProperty('--detail-pos',button.dataset.pos);$$('.product-thumbs button').forEach(x=>x.classList.toggle('active',x===button));$('#galleryCount').textContent=`${index+1} / 3`});
  bindProductCards();
}
function renderCheckout(){
  closeDrawers();const node=$('#checkoutTemplate').content.cloneNode(true);$('#app').replaceChildren(node);showChrome(true);
  if(!cart.length){location.hash='shop';return}
  let sub=cartSubtotal(),promoDiscount=0;
  const renderReviewItems=()=>{sub=cartSubtotal();$('#reviewItems').innerHTML=cart.length?cart.map(x=>{const p=products.find(v=>v.id===x.id);return `<div class="review-row"><div class="review-thumb"></div><span>${p.name}<br><small>${p.id}${x.size?` · ${x.size}`:''} × ${x.qty}</small></span><b>${money(productPrice(p)*x.qty)}</b></div>`}).join(''):'<div class="empty checkout-empty">購物清單已清空<br><small>請先加入商品再完成訂單。</small></div>';$('#reviewSubtotal').textContent=money(sub)};
  renderReviewItems();
  const selectCards=()=>{$$('.option-card').forEach(x=>x.classList.toggle('selected',!!x.querySelector('input:checked')))};
  const updateDelivery=()=>{
    const region=$('input[name="region"]:checked').value,isHK=region==='hongkong',discountedSub=Math.max(0,sub-promoDiscount);
    if(isHK){
      const free=discountedSub>=500;
      $('#phoneLabel').innerHTML='手機號碼（+852） <em class="required-mark">*</em>';$('#checkoutPhone').placeholder='例如：9123 4567';
      $('#deliveryOptions').innerHTML=`<label class="option-card selected"><input type="radio" name="delivery" value="sf" checked><span><strong>${free?'順豐寄付':'順豐到付'}</strong><small>${free?'已達 MOP 500 包郵條件':'運費由收件人支付'}</small></span><b>${free?'免運':'到付'}</b></label>`;
      $('#pickupLabel').innerHTML='順豐站／智能櫃／地址 <em class="required-mark">*</em>';$('#pickupField input').placeholder='輸入順豐網點名稱或香港收貨地址';
      $('#reviewShipping').textContent=free?'免運 · 順豐寄付':'順豐到付';$('#reviewTotal').textContent=money(discountedSub);
    }else{
      const fee=discountedSub>=300?0:25;
      $('#phoneLabel').innerHTML='手機號碼（+853） <em class="required-mark">*</em>';$('#checkoutPhone').placeholder='例如：6688 1234';
      $('#deliveryOptions').innerHTML=`<label class="option-card selected"><input type="radio" name="delivery" value="ebuy" checked><span><strong>eBuy 取貨點</strong><small>滿 MOP 300 免運</small></span><b>${fee?money(fee):'免運'}</b></label><label class="option-card"><input type="radio" name="delivery" value="locker"><span><strong>智能櫃</strong><small>澳門地區</small></span><b>${fee?money(fee):'免運'}</b></label>`;
      $('#pickupLabel').innerHTML='取貨點／智能櫃名稱 <em class="required-mark">*</em>';$('#pickupField input').placeholder='例如：筷子基 eBuy 取貨點';
      $('#reviewShipping').textContent=fee?money(fee):'免運';$('#reviewTotal').textContent=money(discountedSub+fee);
    }
    $$('#deliveryOptions input').forEach(r=>r.onchange=selectCards);selectCards();
  };
  $$('input[name="region"]').forEach(r=>r.onchange=updateDelivery);updateDelivery();
  checkoutCartSync=()=>{renderReviewItems();const submit=$('#checkoutForm button[type="submit"]'),feedback=$('#promoFeedback');if(!cart.length){promoDiscount=0;$('#reviewDiscountRow').hidden=true;$('#reviewShipping').textContent='—';$('#reviewTotal').textContent=money(0);if(submit)submit.disabled=true;if(feedback){feedback.textContent='購物清單已清空，請先加入商品。';feedback.className='promo-feedback error'}return}if(submit)submit.disabled=false;if(promoDiscount>0){if(discountActive()&&sub>=discountSettings.minSpend){promoDiscount=Math.round(sub*discountSettings.codePercent/100);$('#reviewDiscount').textContent=`− ${money(promoDiscount)}`;$('#reviewDiscountRow').hidden=false}else{promoDiscount=0;const button=$('#applyPromo');if(button){button.classList.remove('applied');button.classList.add('invalid');button.textContent='套用'}$('#reviewDiscountRow').hidden=true;if(feedback){feedback.textContent='購物清單已更新，請重新套用優惠碼。';feedback.className='promo-feedback error'}}}updateDelivery()};
  const syncRecipient=()=>{if($('#sameName').checked)$('#recipientName').value=$('#orderName').value};$('#sameName').onchange=()=>{$('#recipientName').readOnly=$('#sameName').checked;syncRecipient();if(!$('#sameName').checked)$('#recipientName').focus()};$('#orderName').oninput=syncRecipient;
  $('#applyPromo').onclick=()=>{const button=$('#applyPromo'),code=$('#promoInput').value.trim().toUpperCase(),feedback=$('#promoFeedback');button.classList.remove('applied','invalid');button.textContent='套用';if(!discountActive()||code!==discountSettings.code.toUpperCase()){promoDiscount=0;button.classList.add('invalid');feedback.textContent='優惠碼無效或活動尚未開始。';feedback.className='promo-feedback error';$('#reviewDiscountRow').hidden=true;updateDelivery();return}if(sub<discountSettings.minSpend){promoDiscount=0;button.classList.add('invalid');feedback.textContent=`此優惠碼需消費滿 ${money(discountSettings.minSpend)}。`;feedback.className='promo-feedback error';$('#reviewDiscountRow').hidden=true;updateDelivery();return}promoDiscount=Math.round(sub*discountSettings.codePercent/100);button.classList.add('applied');button.textContent='已套用';feedback.textContent=`已套用 ${discountSettings.codePercent}% 優惠。`;feedback.className='promo-feedback success';$('#reviewDiscount').textContent=`− ${money(promoDiscount)}`;$('#reviewDiscountRow').hidden=false;updateDelivery()};
  $$('.terms a').forEach(link=>link.onclick=e=>{e.preventDefault();e.stopPropagation();location.hash=link.getAttribute('href')});
  $('#checkoutForm').onsubmit=e=>{
    e.preventDefault();
    const checkoutState=[...e.currentTarget.elements].filter(el=>el.name||el.id).map(el=>({name:el.name,id:el.id,type:el.type,value:el.value,checked:el.checked}));
    const order=`MS${String(Date.now()).slice(-6)}`,total=$('#reviewTotal').textContent;
    const orderedItems=cart.map((item,index)=>({item,product:products.find(product=>product.id===item.id),index})).filter(row=>row.product);
    $('#app').innerHTML=`<section class="payment-demo-page"><nav class="checkout-progress" aria-label="結帳進度"><span class="done"><i>1</i>購物清單</span><span class="active" aria-current="step"><i>2</i>確認及付款</span><span><i>3</i>下單成功</span></nav><div class="payment-demo-grid"><div class="payment-demo-intro"><p class="eyebrow">BANK TRANSFER · DEMO</p><h1>澳門中銀轉帳</h1><p class="payment-demo-copy">請先掃描二維碼完成轉帳，再於下方上傳付款憑證。此頁只作流程示範，以下並非真實收款帳戶。</p><div class="payment-reminder">敬請重覆核實訂單內容，並於下單後 24 小時內上傳付款憑證截圖。</div><dl class="payment-demo-meta"><div><dt>訂單編號</dt><dd>${order}</dd></div><div><dt>付款金額</dt><dd>${total}</dd></div></dl></div><aside class="bank-transfer-card"><div class="demo-data-label">示範資料</div><div class="demo-qr bank-demo-qr" role="img" aria-label="不可使用的澳門中銀示範二維碼"><i></i><i></i><i></i><b>DEMO</b></div><strong class="bank-scan-tip">請用澳門中銀 APP 掃碼轉帳</strong><div class="bank-supplement"><p class="eyebrow">補充轉帳資料</p><dl><div><dt>收款人名稱</dt><dd>MUSIS STUDIO</dd></div><div><dt>銀行戶口號碼</dt><dd>123-456-789012</dd></div></dl><p>正式版本將顯示你在後台「付款設定」中填寫的資料。</p></div></aside><section class="payment-proof-panel" aria-labelledby="paymentProofTitle"><p class="eyebrow">STEP 2 · PAYMENT PROOF</p><h2 id="paymentProofTitle">確認並上傳付款憑證</h2><p>請確認付款金額及收款資料正確，再選擇剛才的付款截圖。</p><div class="payment-proof"><label for="paymentProof">付款憑證截圖 <em class="required-mark">*</em></label><input id="paymentProof" type="file" accept="image/png,image/jpeg,image/webp" required><label class="payment-proof-picker" for="paymentProof"><span>選擇付款憑證</span><small id="paymentProofName">JPG、PNG 或 WEBP，上限 8MB</small></label><p id="paymentProofError" class="payment-proof-error" aria-live="polite"></p></div><div class="payment-proof-preview" id="paymentProofPreviewBox" hidden><img id="paymentProofPreview" alt="所選付款憑證預覽"><div><strong>請確認這是正確的付款憑證</strong><small id="paymentProofPreviewName"></small><button class="text-button" id="removePaymentProof" type="button">移除並重新選擇</button></div></div><div class="payment-demo-actions"><button class="primary" id="completeDemoPayment" type="button" disabled>確認憑證並完成下單 →</button><button class="text-button" id="backToCheckout" type="button">← 返回確認訂單</button></div></section></div></section>`;
    $('.payment-demo-grid h1').textContent='付款方式：澳門中銀轉帳';
    $('.bank-scan-tip').textContent='請使用澳門中銀 APP 掃碼轉帳';
    const bankLabels=$$('.bank-transfer-card dt');if(bankLabels[0])bankLabels[0].textContent='收款名稱';if(bankLabels[1])bankLabels[1].textContent='銀行帳戶號碼';
    const proof=$('#paymentProof'),complete=$('#completeDemoPayment'),proofName=$('#paymentProofName'),proofError=$('#paymentProofError'),proofPreviewBox=$('#paymentProofPreviewBox'),proofPreview=$('#paymentProofPreview'),proofPreviewName=$('#paymentProofPreviewName');
    let proofPreviewUrl='';const releaseProofPreview=()=>{if(proofPreviewUrl){URL.revokeObjectURL(proofPreviewUrl);proofPreviewUrl=''}};const resetProof=(clearInput=true)=>{releaseProofPreview();if(clearInput)proof.value='';proofName.textContent='JPG、PNG 或 WEBP，上限 8MB';proofPreview.removeAttribute('src');proofPreviewBox.hidden=true;proofPreviewName.textContent='';complete.disabled=true};
    $('#backToCheckout').onclick=()=>{releaseProofPreview();renderCheckout();const region=checkoutState.find(item=>item.name==='region'&&item.checked);if(region){const control=$(`input[name="region"][value="${region.value}"]`);if(control){control.checked=true;control.dispatchEvent(new Event('change'))}}checkoutState.forEach(item=>{const control=item.id?document.getElementById(item.id):item.name?document.querySelector(`[name="${item.name}"][value="${item.value}"]`)||document.querySelector(`[name="${item.name}"]`):null;if(!control)return;if(item.type==='radio'||item.type==='checkbox')control.checked=item.checked;else control.value=item.value});const delivery=document.querySelector('input[name="delivery"]:checked');if(delivery)delivery.dispatchEvent(new Event('change'));const same=document.getElementById('sameName');if(same)same.dispatchEvent(new Event('change'));window.scrollTo(0,0)};
    $('#removePaymentProof').onclick=()=>{resetProof();proofError.textContent='';proof.focus()};
    proofPreview.onload=()=>{if(proofPreviewUrl)complete.disabled=false};proofPreview.onerror=()=>{resetProof();proofError.textContent='無法讀取這張圖片，請重新選擇付款憑證。'};
    proof.onchange=()=>{const file=proof.files[0],allowedTypes=['image/jpeg','image/png','image/webp'];proofError.textContent='';resetProof(false);if(!file)return;if(!allowedTypes.includes(file.type)){proof.value='';proofError.textContent='只接受 JPG、PNG 或 WEBP 圖片。';return}if(file.size>8*1024*1024){proof.value='';proofError.textContent='圖片不可超過 8MB，請壓縮後重新選擇。';return}proofPreviewUrl=URL.createObjectURL(file);proofPreview.src=proofPreviewUrl;proofPreviewBox.hidden=false;proofName.textContent=file.name;proofPreviewName.textContent=file.name};
    complete.onclick=()=>{
      if(!proof.files.length){proofError.textContent='請先上傳付款憑證截圖。';return}
      const itemDetails=orderedItems.map(({item,product,index})=>`<article class="success-order-item"><div class="success-order-image" style="${imageStyle(product,index)}"></div><div><small>${product.id} · 925 SILVER</small><h2>${product.name}</h2><p>數量：${item.qty}</p></div><strong>${money(productPrice(product)*item.qty)}</strong></article>`).join('');
      releaseProofPreview();$('#app').innerHTML=`<section class="shop-head checkout-success"><nav class="checkout-progress" aria-label="結帳進度"><span class="done"><i>1</i>購物清單</span><span class="done"><i>2</i>確認及付款</span><span class="active" aria-current="step"><i>3</i>下單成功</span></nav><div class="success-heading"><p class="eyebrow">ORDER CREATED · DEMO</p><h1>下單成功</h1><p class="success-order-number">訂單編號：<strong>${order}</strong></p></div><div class="success-order-details"><p class="eyebrow">ORDER DETAILS · 訂購商品詳情</p>${itemDetails}<div class="success-order-total"><span>訂單總額</span><strong>${total}</strong></div><p class="success-thanks">謝謝你的購買，我們會盡快確認訂單</p></div><div class="demo-notice">付款憑證已上傳。正式版本會在後台建立待確認訂單，並自動寄出確認 Email。</div><a class="primary" href="#order">查詢訂單流程 →</a></section>`;
      cart=[];saveCart();window.scrollTo(0,0)
    };
    window.scrollTo(0,0)
  }
}
function renderAdmin(){closeDrawers();const node=$('#adminTemplate').content.cloneNode(true);$('#app').replaceChildren(node);showChrome(false);const orders=[['MS260928','陳小姐 · 2 件','MOP 436','5 分鐘前','待核款'],['MS260924','Joana · 1 件','MOP 278','18 分鐘前','待核款'],['MS260919','Wong · 3 件','MOP 674','42 分鐘前','資料不符']];$('#adminOrders').innerHTML=orders.map((o,i)=>`<div class="table-row"><b>${o[0]}</b><span>${o[1]}</span><span>${o[2]}</span><small>${o[3]}</small><button class="confirm" data-order="${o[0]}">${i===2?'檢查':'確認收款'}</button></div>`).join('');$('#adminProducts').innerHTML=products.slice(0,5).map(p=>`<div class="table-row"><b>${p.id}</b><span>${p.name}</span><span>${productPrice(p)<p.price?`<del>${money(p.price)}</del> ${money(productPrice(p))}`:money(p.price)}</span><span class="status ${p.stock<=2?'low':''}">${p.preorder?'預訂':p.stock?`庫存 ${p.stock}`:'售罄'}</span><button class="text-button">編輯</button></div>`).join('');$$('.confirm').forEach(b=>b.onclick=()=>{b.textContent='已確認';b.disabled=true;toast(`${b.dataset.order} 已標記為已付款`)});$('#newProduct').onclick=()=>toast('正式版本會開啟新增商品表單');
  $('#ringSizeAdmin').innerHTML=products.filter(p=>p.cat==='rings').map(p=>`<label><span>${p.id} · ${p.name}</span><input data-ring-size="${p.id}" value="${productSizes(p).join('、')}" placeholder="例如：均碼・開口戒 或 10、12、14"></label>`).join('');
  $('#saveRingSizes').onclick=()=>{const next={};$$('[data-ring-size]').forEach(input=>{const values=input.value.split(/[、,，]/).map(x=>x.trim()).filter(Boolean);next[input.dataset.ringSize]=values.length?values:['均碼・開口戒']});ringSizeSettings={...ringSizeSettings,...next};localStorage.setItem('musis-ring-sizes',JSON.stringify(ringSizeSettings));toast('戒指尺寸設定已更新')};
  $('#discountProduct').innerHTML=products.map(p=>`<option value="${p.id}">${p.id} · ${p.name}</option>`).join('');$('#discountEnabled').checked=discountSettings.enabled;$('#discountProduct').value=discountSettings.productId;$('#discountSalePrice').value=discountSettings.salePrice;$('#discountCode').value=discountSettings.code;$('#discountPercent').value=discountSettings.codePercent;$('#discountMinimum').value=discountSettings.minSpend;$('#discountStart').value=discountSettings.start;$('#discountEnd').value=discountSettings.end;
  $('#saveDiscount').onclick=()=>{discountSettings={enabled:$('#discountEnabled').checked,productId:$('#discountProduct').value,salePrice:Number($('#discountSalePrice').value),code:$('#discountCode').value.trim().toUpperCase(),codePercent:Number($('#discountPercent').value),minSpend:Number($('#discountMinimum').value),start:$('#discountStart').value,end:$('#discountEnd').value};localStorage.setItem('musis-discount',JSON.stringify(discountSettings));announcements[2]=discountSettings.enabled?`限時優惠進行中 · 結帳輸入優惠碼 ${discountSettings.code}`:'';localStorage.setItem('musis-announcements',JSON.stringify(announcements));startAnnouncementCarousel();saveCart();toast('折扣活動及公告已同步');renderAdmin()};
  [$('#announcement1'),$('#announcement2'),$('#announcement3')].forEach((input,index)=>input.value=announcements[index]||'');$('#saveAnnouncements').onclick=()=>{announcements=[$('#announcement1').value.trim(),$('#announcement2').value.trim(),$('#announcement3').value.trim()];localStorage.setItem('musis-announcements',JSON.stringify(announcements));startAnnouncementCarousel();toast('頂部公告已更新')};
  $('#aboutTitle').value=aboutSettings.title;$('#aboutBody').value=aboutSettings.body;$('#aboutCareTitle').value=aboutSettings.careTitle;$('#aboutCareBody').value=aboutSettings.careBody;$('#saveAbout').onclick=()=>{const save=image=>{aboutSettings={title:$('#aboutTitle').value.trim(),body:$('#aboutBody').value.trim(),careTitle:$('#aboutCareTitle').value.trim(),careBody:$('#aboutCareBody').value.trim(),image:image||aboutSettings.image};localStorage.setItem('musis-about',JSON.stringify(aboutSettings));toast('關於頁面已更新')},file=$('#aboutImage').files[0];if(!file)return save();const reader=new FileReader();reader.onload=()=>save(reader.result);reader.readAsDataURL(file)}
}
function renderAbout(){showChrome(true);$('#app').innerHTML=`<section class="story-band about-story reveal" style="--about-image:url('${aboutSettings.image}')"><div class="about-copy"><p class="eyebrow">ABOUT MUSIS</p><h2>${aboutSettings.title}</h2><p>${aboutSettings.body}</p><p><strong>${aboutSettings.careTitle}</strong><br>${aboutSettings.careBody}</p><a class="about-cta" href="#shop">探索飾品 →</a></div></section>`}
function renderCare(){showChrome(true);$('#app').innerHTML=`<section class="info-page reveal"><p class="eyebrow">JEWELLERY CARE</p><h1>保養建議</h1><div class="info-grid"><article><b>01</b><h2>日常佩戴</h2><p>避免香水、酒精、清潔劑和溫泉；運動、洗澡及睡覺前先取下飾品。</p></article><article><b>02</b><h2>清潔純銀</h2><p>以柔軟拭銀布順同一方向輕擦。天然珍珠及水晶部分不宜使用洗銀水。</p></article><article><b>03</b><h2>妥善收納</h2><p>清潔並保持乾燥後，獨立放入密封袋，避免不同飾品互相刮擦。</p></article></div></section>`}
function renderGuide(){showChrome(true);$('#app').innerHTML=`<section class="info-page reveal"><p class="eyebrow">SHOPPING GUIDE</p><h1>購買須知</h1><div class="info-grid"><article><b>ORDER</b><h2>下單與付款</h2><p>提交訂單後請按頁面指示完成轉帳。付款資料經人工確認後，訂單狀態會更新為已付款；客戶可使用電話號碼及訂單編號查詢進度。</p></article><article><b>PRODUCT</b><h2>現貨與預訂</h2><p>現貨會在確認付款後安排備貨；預訂款一般約 7 個工作天到貨。如訂單同時包含現貨及預訂商品，預設待商品齊全後一併寄出。</p></article><article><b>RETURNS</b><h2>天然材質與退換</h2><p>天然水晶、珍珠的顏色及紋理各有差異，並非品質問題。耳環基於衛生理由，除品質異常或寄錯商品外不設退換。如收到品質異常、缺件或寄錯商品，請在收貨後 7 日內聯絡 MUSIS。</p></article></div></section>`}
function renderShipping(){showChrome(true);$('#app').innerHTML=`<section class="info-page reveal"><p class="eyebrow">DELIVERY</p><h1>運送服務</h1><div class="info-grid"><article><b>MACAU</b><h2>澳門地區</h2><p>eBuy 取貨點或智能櫃；訂單滿 MOP 300 免運。現貨訂單確認付款後安排出貨。</p></article><article><b>HONG KONG</b><h2>香港地區</h2><p>順豐配送；未滿 MOP 500 默認順豐到付，滿 MOP 500 則由 MUSIS 寄付運費。</p></article><article><b>PRE-ORDER</b><h2>預訂商品</h2><p>一般約 7 個工作天到貨；如與現貨商品一起購買，預設待商品齊全後一併寄出。</p></article></div></section>`}
function renderOrderLookup(){showChrome(true);const node=$('#orderTemplate').content.cloneNode(true);$('#app').replaceChildren(node);const form=$('#orderLookupForm'),result=$('#orderLookupResult'),error=$('#lookupError');form.onsubmit=e=>{e.preventDefault();const phone=$('#lookupPhone').value.replace(/\D/g,''),number=$('#lookupNumber').value.trim().toUpperCase();error.textContent='';result.hidden=true;if(!phone||!number){error.textContent='請輸入電話號碼及訂單編號。';return}if(phone!=='66881234'||number!=='MS260928'){error.textContent='找不到相符訂單，請檢查電話號碼及訂單編號。';return}form.hidden=true;result.hidden=false;result.innerHTML=`<div class="result-head"><div><p class="eyebrow">ORDER ${number}</p><h2>備貨中</h2></div><span class="status-chip">已付款</span></div><dl class="order-meta"><div><dt>下單日期</dt><dd>2026年9月28日</dd></div><div><dt>收貨方式</dt><dd>eBuy 取貨點</dd></div><div><dt>訂單金額</dt><dd>MOP 436</dd></div></dl><div class="order-timeline"><div class="timeline-step done"><i></i><div><b>訂單已建立</b><small>9月28日 · 14:20</small></div></div><div class="timeline-step done"><i></i><div><b>付款已確認</b><small>9月28日 · 16:05</small></div></div><div class="timeline-step current"><i></i><div><b>商品備貨中</b><small>預計 1–2 個工作天完成</small></div></div><div class="timeline-step"><i></i><div><b>等待寄出</b><small>寄出後會顯示取貨資料</small></div></div></div><button class="text-button lookup-again" type="button">← 查詢另一張訂單</button>`;result.querySelector('.lookup-again').onclick=()=>{result.hidden=true;form.hidden=false;form.reset();$('#lookupPhone').focus()}}}
function showChrome(show){$('.site-header').style.display=show?'grid':'none';$('.announcement').style.display=show?'block':'none';$('footer').style.display=show?'grid':'none'}
function router(){clearInterval(heroCarouselTimer);checkoutCartSync=null;const route=(location.hash.slice(1).split('?')[0]||'home');({home:renderHome,shop:renderShop,new:renderNew,hot:renderHot,favorites:renderFavorites,product:renderProduct,checkout:renderCheckout,admin:renderAdmin,about:renderAbout,guide:renderGuide,care:renderCare,shipping:renderShipping,order:renderOrderLookup}[route]||renderHome)();window.scrollTo(0,0)}
$('#cartButton').onclick=openCart;$('#cartClose').onclick=closeDrawers;$('#scrim').onclick=closeDrawers;$('#checkoutButton').onclick=e=>{if(!cart.length){e.preventDefault();toast('請先選擇商品');return}closeDrawers();if(location.hash==='#checkout'){e.preventDefault();router()}};$('.menu-button').onclick=()=>{$('#mobileDrawer').classList.add('open');$('#scrim').classList.add('open')};$('.mobile-drawer .drawer-close').onclick=closeDrawers;$$('.mobile-drawer a').forEach(a=>a.onclick=closeDrawers);window.addEventListener('hashchange',router);saveCart();saveFavorites();startAnnouncementCarousel();router();
